version: '3'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379

  celery_app:
    build:
      context: .
    image: celery_app

  # Common configuration for Celery workers
  x-celery-worker:
    &celery_worker
    image: celery_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  test_01:
    <<: *celery_worker
    command: celery -A app.01_shutdown:app worker

  test_02:
    <<: *celery_worker
    command: celery -A app.02_exit:app worker

  test_03:
    <<: *celery_worker
    command: celery -A app.03_sleep_and_shutdown:app worker

  test_04:
    <<: *celery_worker
    command: celery -A app.04_sleep_and_exit:app worker

  test_05:
    <<: *celery_worker
    command: celery -A app.05_shutdown_exit:app worker

  test_06:
    <<: *celery_worker
    command: celery -A app.06_sleep_and_shutdown_exit:app worker

